// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6GlcntPdrM3jVhfEZLDkGHq7aO3PfHmY',
    appId: '1:1025587976060:android:30faf850212588354f36f9',
    messagingSenderId: '1025587976060',
    projectId: 'uny-app-312bf',
    storageBucket: 'uny-app-312bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD8urKgPu1rQPoeprTSuLXeIbFsZXaZsU',
    appId: '1:1025587976060:ios:d3d3c7b478eb43ad4f36f9',
    messagingSenderId: '1025587976060',
    projectId: 'uny-app-312bf',
    storageBucket: 'uny-app-312bf.appspot.com',
    iosClientId: '1025587976060-tvqjn5okipfcbdhbb96250rm7pupgg64.apps.googleusercontent.com',
    iosBundleId: 'com.estimators.unyapp',
  );

}
