class Constants{

  static const SIMPLE_RESPONSE_CONVERTER = 'SIMPLE_RESPONSE_CONVERTER';

  static const AUTH_MODEL_CONVERTER_CONSTANT = 'AUTH_MODEL_CONVERTER';

  static const USER_DATA_MODEL_CONVERTER_CONSTANT = 'USER_DATA_MODEL_CONVERTER';

  static const ALL_USER_DATA_MODEL_CONVERTER_CONSTANT = 'ALL_USER_DATA_MODEL_CONVERTER';

  static const INTERESTS_MODEL_CONVERTER = 'INTERESTS_MODEL_CONVERTER';

  static const PHOTO_SEARCH_MODEL_CONVERTER = 'PHOTO_SEARCH_MODEL_CONVERTER';

  static const ALL_MESSAGES_MODEL_CONVERTER = 'ALL_MESSAGES_MODEL_CONVERTER';

  static const ROOM_MESSAGES_CONVERTER = 'ROOM_MESSAGES_CONVERTER';

  static const SIMPLE_MESSAGE_CONVERTER = 'SIMPLE_MESSAGE_CONVERTER';

  static const MATCHES_JSON_CONVERTER = 'MATCHES_JSON_CONVERTER';

  static const FILTER_USER_MODEL_CONVERTER = 'FILTER_USER_MODEL_CONVERTER';
}