class Constants{

  static const SIMPLE_RESPONSE_CONVERTER = 'SIMPLE_RESPONSE_CONVERTER';

  static const AUTH_MODEL_CONVERTER_CONSTANT = 'AUTH_MODEL_CONVERTER';

  static const USER_DATA_MODEL_CONVERTER_CONSTANT = 'USER_DATA_MODEL_CONVERTER';

  static const ALL_USER_DATA_MODEL_CONVERTER_CONSTANT = 'ALL_USER_DATA_MODEL_CONVERTER';

  static const INTERESTS_MODEL_CONVERTER = 'INTERESTS_MODEL_CONVERTER';

  static const PHOTO_SEARCH_MODEL_CONVERTER = 'PHOTO_SEARCH_MODEL_CONVERTER';
}