// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8HGcrQe8IOD-24o8yd4Qd8gGMM8e0BwE',
    appId: '1:1025587976060:web:7bc28f008e12caa74f36f9',
    messagingSenderId: '1025587976060',
    projectId: 'uny-app-312bf',
    authDomain: 'uny-app-312bf.firebaseapp.com',
    storageBucket: 'uny-app-312bf.appspot.com',
    measurementId: 'G-Y59CQNBB0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6GlcntPdrM3jVhfEZLDkGHq7aO3PfHmY',
    appId: '1:1025587976060:android:30faf850212588354f36f9',
    messagingSenderId: '1025587976060',
    projectId: 'uny-app-312bf',
    storageBucket: 'uny-app-312bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD8urKgPu1rQPoeprTSuLXeIbFsZXaZsU',
    appId: '1:1025587976060:ios:d3d3c7b478eb43ad4f36f9',
    messagingSenderId: '1025587976060',
    projectId: 'uny-app-312bf',
    storageBucket: 'uny-app-312bf.appspot.com',
    iosClientId: '1025587976060-tvqjn5okipfcbdhbb96250rm7pupgg64.apps.googleusercontent.com',
    iosBundleId: 'com.estimators.unyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD8urKgPu1rQPoeprTSuLXeIbFsZXaZsU',
    appId: '1:1025587976060:ios:b7e72ca6309fa5384f36f9',
    messagingSenderId: '1025587976060',
    projectId: 'uny-app-312bf',
    storageBucket: 'uny-app-312bf.appspot.com',
    iosClientId: '1025587976060-t6ntcqgql4oqs2doi3tsar3llf0v5j7c.apps.googleusercontent.com',
    iosBundleId: 'com.estimators.unyapp.unyApp',
  );
}
